version: '3'

services:
  django-app:
    image: django-app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
